### ISSUE TITLE
Identify the membrane-bound or secreted forms of immunoglobulin

### ISSUE THREAD

**Issue by TangLabsysu2020** [KCCG/rageseq#2]
Hi,
     Thanks for your wondful work. I have read the paper published in 2019 "High-throughput targeted long-read single cell
sequencing reveals the clonal and transcriptional landscape of lymphocytes", and have a small doubt. How to Identify the membrane-bound or secreted forms of immunoglobulin use the information of alternative splicing at the 3’
end.
    Thanks

**Comment by noncodo** [comment]
The transmembrane domain of BCRs is on the 5' end, which can be detected
following the long read sequencing step (and de novo assembly).

**Comment by TangLabsysu2020** [comment]
Hi
    Thanks for your prompt reply. Maybe I didn’t express my doubt very clearly, can i simply blast the transmembrane nucleotide sequence with the full-length reads, then define the reads contains the transmembrane nucleotide sequence as membrane-bound, otherwise secreted.
Thanks

**Comment by noncodo** [comment]
Yes that makes sense. You may want to blast the assembled contigs, as the
PCR tends to generate fragmented reads.

**Comment by TangLabsysu2020** [comment]
Thanks, I'll have a try
